name: Build and Deploy Container App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2

   

    - uses: azure/docker-login@v1
      with:
        login-server: niqacr.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t niqacr.azurecr.io/app1
        docker push niqacr.azurecr.io/app1
